site_name: Athenian FRC Robotics
site_url: http://www.athenian-robotics.org
site_description: Athenian FRC Robotics Documentation
site_author: Athenian FRC Robotics Team

repo_url: https://github.com/athenian-robotics/athenian-robotics-mkdocs
repo_name: 'GitHub Home'

nav:
  - Home: index.md
  - Overview: overview.md
  - Github Repos:
    - FRC Robotics: https://github.com/athenian-robotics
    - Programming Tutorials: https://github.com/athenian-programming
  - Coding Resources: coding-resources.md
  - Languages:
    - Python:
      - Learning: learning-python.md
      - Exercises:
        - Basics: python-basics.md
        - Conditionals: python-conditionals.md
        - Lists: python-lists.md
        - Dictionaries: python-dictionaries.md
        - Iterations: python-iterations.md
        - Functions: python-functions.md
      - Setup: python-setup.md
      - Posts: python.md
    - Kotlin: kotlin.md
    - C: clang.md
  - Operating Systems:
    - OSX: osx-setup.md
    - Linux:
      - Raspbian: raspbian.md
      - Ubuntu: ubuntu.md
      - Generic Linux: linux.md
      - Linux Commands:
        - ssh: ssh.md
        - apt: apt.md
    - Unix: unix.md
  - ROS:
    - Installation: ros-installation.md
    - Commands: ros-commands.md
    - ROS Serial: ros-serial.md
    - Miscellaneous: ros-misc.md
    - ROS Master SD Card: ros-master.md
    - Gazebo: gazebo.md
  - Circuit Playground:
    - Crickit/CPX and CircuitPython: circuitpython.md
  - Software:
    - Links: software-links.md
    - Software Services: services.md
    - Git: git.md
    - Jupyter Notebooks: jupyter.md
    - Docker: docker.md
    - Kubernetes: kubernetes.md
    - Istio: istio.md
    - gRPC: grpc.md
    - OpenCV: opencv.md
    - GraphQL: graphql.md
    - Flutter: flutter.md
    - RoboMaker: robomaker.md
    - FAAS: faas.md
    - PyQt5: pyqt5.md
    - nginx: nginx.md
    - Gradle: gradle.md
    - Prometheus: prometheus.md
    - Grafana: grafana.md
    - Markdown: markdown.md
    - MkDocs: mkdocs.md
    - Databases: databases.md
    - Web Services: webservices.md
    - Web Content: webcontent.md
    - Plot.ly: plotly.md
    - XQuartz: xquartz.md
    - AI Projects: ai-projects.md
  - Hardware:
    - Raspberry Pi Zero W: raspipizero.md
    - Raspi Hats: raspihats.md
    - Sensors: sensors.md
    - SD Cards: sd-cards.md
    - Arduino: arduino.md
    - Metro Mini: metro-mini.md
    - Blinkt: blinkt.md
    - Logitech Joystick: joystick.md
    - Nvidia Jetson TX2: jetsontx2.md
    - roboRIO: roborio.md
    - Intel Euclid: euclid.md
    - NeoTrellis M4: trellis.md
    - Adafruit Circuit Playground: circuitplayground.md
    - BBC micro:bit: microbit.md
  - Tutorials:
    - vim: vim.md
    - Shell: shell.md
    - Machine Learning: ml.md
  - Robots:
    - Magni: magni.md
    - TurtleBot3: turtlebot3.md
    - GoPiGo: gopigo.md
    - EV3:
      - Admin: ev3-admin.md
      - Python: ev3-python.md
      - ROS: ev3-ros.md
  - FRC:
    - Networking: frc-networking.md
  - Battlesnake: battlesnake.md
  - Robotics: robotics.md
  - CodinGame Tips: codingame.md
  - Hour of Code: hoc.md
  - Nand To Tetris: nand2tetris.md
  - Education:
    - Robots: education-robots.md
    - Software: education-software.md
  - Miscellaneous: miscellaneous.md

theme:
  name: 'material'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/owls.jpg'
  favicon: 'assets/images/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

google_analytics: ['UA-90285378-1', 'auto']

